name: Continuous Integration

on:
  pull_request:
  push:
    branches: 
      - main

env:
  # /opt/homebrew/opt/llvm@20/ is for macOS
  MLIR_SYS_200_PREFIX: /home/linuxbrew/.linuxbrew/opt/llvm@20/
  TABLEGEN_200_PREFIX: /home/linuxbrew/.linuxbrew/opt/llvm@20/
  RUSTFLAGS: '-L /home/linuxbrew/.linuxbrew/opt/llvm@20/lib -Zsanitizer=address'
  LLZK_SYS_ENABLE_WHOLE_ARCHIVE: 1
  ASAN_OPTIONS: 'detect_odr_violation=2:symbolize=1'
  LSAN_OPTIONS: ''
  ASAN_SYMBOLIZER_PATH: /home/linuxbrew/.linuxbrew/opt/llvm@20/bin/llvm-symbolizer

jobs:
  asan-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          large-packages: false
      - uses: Homebrew/actions/setup-homebrew@master
      - name: Cache homebrew downloads
        uses: actions/cache@v4
        with: 
          path: ~/.cache/Homebrew/
          # It's not the greatest key in the world but works
          key: ${{ runner.os }}-homebrew-${{ hashFiles('**/Cargo.lock') }}
      - name: Install LLVM & MLIR
        run: brew install llvm@20
      - run: /home/linuxbrew/.linuxbrew/opt/llvm@20/bin/llvm-config --version
      - name: Cache cargo crates
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-asan-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Set LSAN_OPTIONS
        run: |
          supp=$(pwd)/.lsan.supp
          if [ -e "$supp" ]; then 
            echo "::debug::Set suppressions file to $supp"
            echo LSAN_OPTIONS="$LSAN_OPTIONS:suppressions=$supp" >> $GITHUB_ENV
          fi
      - name: Build in asan mode
        run: cargo +nightly build --target=x86_64-unknown-linux-gnu --profile=dev --all-features
      - name: Run tests in asan mode
        run: cargo +nightly test --target=x86_64-unknown-linux-gnu --profile=dev --all-features
